version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-website-api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_website
      - POSTGRES_SSL_MODE=disable
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24h
      - JWT_REFRESH_SECRET=your-refresh-secret-key
      - JWT_REFRESH_EXPIRATION=168h
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: personal-website-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_website
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 